# Generated by Django 2.2.3 on 2019-07-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('referenceno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sendername', models.CharField(max_length=50)),
                ('senderaddress', models.TextField()),
                ('sendercontactno', models.CharField(max_length=15)),
                ('receivername', models.CharField(max_length=50)),
                ('receiveraddress', models.TextField()),
                ('source', models.CharField(max_length=200)),
                ('currentcity', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('posteddate', models.CharField(max_length=30)),
            ],
        ),
    ]
